name: aid
description: A sample command-line application.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.7

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  http: ^1.1.2

dev_dependencies:
  lints: ^2.0.0
